
version: '3.2'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kinvo-project-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"